import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#0b122d",
    alignItems: "center",
    justifyContent: "center",
    padding: 20,
  },
  card: {
    width: "100%",
    maxWidth: 360,
    backgroundColor: "#111a3a",
    borderRadius: 18,
    padding: 24,
    alignItems: "center",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.25,
    shadowRadius: 15,
    elevation: 6,
  },
  title: {
    fontSize: 28,
    fontWeight: "900",
    color: "#ffffff",
    marginBottom: 8,
  },
  subtitle: {
    fontSize: 14,
    color: "#c3cddb",
    textAlign: "center",
    marginBottom: 20,
  },
  input: {
    width: "100%",
    height: 48,
    borderRadius: 12,
    backgroundColor: "#1a274a",
    color: "#f8fbff",
    paddingHorizontal: 14,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: "#2f466f",
  },
  passwordInputContainer: {
    width: "100%",
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 12,
  },
  passwordInput: {
    flex: 1,
    height: 48,
    borderRadius: 12,
    backgroundColor: "#1a274a",
    color: "#f8fbff",
    paddingHorizontal: 14,
    paddingRight: 50, // Space for the button
    borderWidth: 1,
    borderColor: "#2f466f",
  },
  visibilityButton: {
    position: "absolute",
    right: 10,
    height: 48,
    width: 30,
    alignItems: "center",
    justifyContent: "center",
  },
  visibilityIcon: {
    fontSize: 18,
    color: "#c3cddb",
  },
  button: {
    marginTop: 10,
    height: 52,
    width: "100%",
    backgroundColor: "#5c6df1",
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
  },
  buttonText: {
    fontSize: 16,
    fontWeight: "bold",
    color: "#ffffff",
  },
  footerRow: {
    marginTop: 14,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
  },
  footerText: {
    color: "#aec1e6",
    fontSize: 13,
  },
  footerLink: {
    color: "#77a4ff",
    fontSize: 13,
    fontWeight: "700",
  },
});
