import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#0b122d",
    padding: 20,
    paddingTop: 50,
  },
  headerRow: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 20,
    width: "100%",
  },
  backButton: {
    width: 40,
    height: 40,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 20,
    backgroundColor: "rgba(255,255,255,0.08)",
  },
  backButtonText: {
    fontSize: 22,
    color: "#cccccc",
    fontWeight: "700",
    lineHeight: 22,
  },
  studentName: {
    fontSize: 20,
    fontWeight: "700",
    color: "#ffffff",
    marginLeft: 12,
    flex: 1,
    flexWrap: "wrap",
  },
  className: {
    fontSize: 20,
    fontWeight: "700",
    color: "#ffffff",
    marginLeft: 12,
    flex: 1,
    flexWrap: "wrap",
  },
  card: {
    width: "100%",
    backgroundColor: "#111a3a",
    borderRadius: 16,
    padding: 20,
    marginBottom: 20,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.08)",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.25,
    shadowRadius: 8,
    elevation: 6,
  },
  title: {
    fontSize: 24,
    fontWeight: "800",
    color: "#ffffff",
    marginBottom: 10,
  },
  centerView: {
    flex: 1,
    width: "100%",
    borderRadius: 14,
    backgroundColor: "rgba(255,255,255,0.03)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.1)",
    justifyContent: "center",
    alignItems: "center",
    padding: 20,
  },
  classCard: {
    width: "100%",
    backgroundColor: "rgba(255,255,255,0.05)",
    borderRadius: 12,
    padding: 12,
    marginBottom: 12,
    borderColor: "rgba(255,255,255,0.15)",
    borderWidth: 1,
  },
  instructorName: {
    color: "#dce2f5",
    fontSize: 16,
    marginBottom: 4,
    fontWeight: "700",
  },
  commentText: {
    color: "#b6c2e1",
    fontSize: 14,
    marginBottom: 4,
  },
  dateText: {
    color: "#8fa6d1",
    fontSize: 12,
  },
  emptyText: {
    color: "#a9b8d6",
    fontSize: 15,
    textAlign: "center",
    marginTop: 10,
  },
  bottomContainer: {
    width: "100%",
    paddingBottom: 30,
    justifyContent: "flex-end",
    alignItems: "center",
  },
  createClassButton: {
    backgroundColor: "#0f56d1",
    paddingVertical: 14,
    marginTop: 20,
    paddingHorizontal: 48,
    borderRadius: 10,
    alignItems: "center",
    justifyContent: "center",
    shadowOpacity: 0.4,
    shadowRadius: 8,
    elevation: 8,
  },
  createClassButtonText: {
    color: "#ffffff",
    fontSize: 16,
    fontWeight: "bold",
  },
  deleteButton: {
    backgroundColor: "#4c1711",
    paddingVertical: 14,
    marginTop: 20,
    paddingHorizontal: 48,
    borderRadius: 10,
    alignItems: "center",
    justifyContent: "center",
    shadowOpacity: 0.4,
    shadowRadius: 8,
    elevation: 8,
  },
  deleteButtonText: {
    color: "#ffffff",
    fontSize: 16,
    fontWeight: "bold",
  },
});
